"""add composite index on created_at id

Revision ID: 289774487a98
Revises: 9f42471d77bd
Create Date: 2026-06-29 00:40:43.526748

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '289774487a98'
down_revision: str | None = '9f42471d77bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('ix_tickets_created_at_id', ['created_at', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index('ix_tickets_created_at_id')

    # ### end Alembic commands ###
